options:
  zuul-branch:
    type: string
    default: ""
    description: "Zuul branch."
  zuul-project:
    type: string
    default: ""
    description: "Zuul project."
  zuul-url:
    type: string
    default: ""
    description: "Zuul URL."
  zuul-ref:
    type: string
    default: ""
    description: "Zuul ref."
  zuul-change:
    type: string
    default: ""
    description: "Zuul change."
  pypi-mirror:
    type: string
    defualt: ""
    description: "Python Package Index mirror."
  download-mirror:
    type: string
    default: "http://dl.openstack.tld/"
    description: "Download mirror."
  wheel-mirror:
    type: string
    default: "http://dl.openstack.tld/wheels"
    description: "Python wheel packages mirror."
  git-user-email:
    type: string
    default: "hyper-v_ci@microsoft.com"
    description: "Value to pass to user.email git config."
  git-user-name:
    type: string
    default: "Hyper-V CI"
    description: "Value to pass to user.name git config."
  vmswitch-name:
    default: br100
    type: string
    description: Virtual switch to use
  data-port:
    type: string
    default: ""
    description: |
      Ethernet interface to use for vmswitch. This can be a MAC address or an interface name.
      This option is mandatory if more then one interface is present on the target system.
      In cases where there is only one interface on the system, the vmswitch will be created using that
      interface and OSManagement will be set to True, regardless of the vmswitch-management option.
      Avoid using the management interface as a data interface where system has more then one NIC.
  vmswitch-management:
    default: False
    type: boolean
    description: |
      Allow management OS on this vm switch. If True, the switch will be set in DHCP mode.
  extra-python-packages:
    default: ""
    type: string
    description: "Extra python packages to install."
  ad-user-name:
    default: ""
    type: string
    description: "User name of the AD user that will be used by this Hyper-V node."
  git-url:
    type: string
    default: "https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20150319/Git-1.9.5-preview20150319.exe"
    description: |
      URL used to download git for Windows. Optionally, a checksum supported
      by the 'Get-FileHash' PowerShell cmdlet can be provided to check file
      integrity.
      Syntax is: "<url>#<hash_algorithm><checksum>"
  python27-url:
    type: string
    default: "https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi"
    description: |
      URL used to download Python 2.7.x for Windows. Optionally, a checksum
      supported by the 'Get-FileHash' PowerShell cmdlet can be provided to
      check file integrity.
      Syntax is: "<url>#<hash_algorithm><checksum>"
  7z-url:
    type: string
    default: "http://www.7-zip.org/a/7z938.exe"
    description: |
      URL used to download 7z installer for Windows. Optionally, a checksum
      supported by the 'Get-FileHash' PowerShell cmdlet can be provided to
      check file integrity.
      Syntax is: "<url>#<hash_algorithm><checksum>"
  enable-freerdp-console:
    type: boolean
    default: True
    description: |
      Utility to connect to the console of a VM.
  vc-2012-url:
    type: string
    default: "http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe"
    description: |
      This is required only when config option 'enable-freerdp-console' is set to True.
      URL used to download Visual C++ 2012 x86 runtime. Optionally, a checksum
      supported by the 'Get-FileHash' PowerShell cmdlet can be provided to
      check file integrity.
      Syntax is: "<url>#<hash_algorithm><checksum>".
